

# This file was *autogenerated* from the file /mnt/c/Users/seoji/code/sage/BalancedPair.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1000 = Integer(1000); _sage_const_1 = Integer(1); _sage_const_30 = Integer(30)
from sage.combinat.words import *

def Reset_balanced_vector(s):
    """
    Calculate the balanced vector of a word.
    
    Args:
        self (Word): The input word.
    
    Returns:
        dict: The balanced vector of the word.
    """  
    # print("self:", self)
    balanced_vector = {key: _sage_const_0  for key in s.parent().alphabet()}
    return balanced_vector

def Balanced_pair_list(s,t, n=_sage_const_1000 ):
    """
    Check if the given string has balanced pairs of infinite words using Word from Sage.
    
    Args:
        s,t (word): The input infinite words.
    
    Returns:
        Alphabet: The Balanced Pair of 2 infinite words.
    """  
    if s.parent().alphabet() != t.parent().alphabet() :
        raise ValueError("The two words must have the same alphabet.")
    min_length = min(s.length(), t.length(), n)
    # print("min_length:", min_length)
    head = _sage_const_0 
    startpos = _sage_const_0 
    A = []
    s.balanced_vector = Reset_balanced_vector(s) 
    t.balanced_vector = Reset_balanced_vector(t) 
    for head in range(min_length):
            # print("subword_s:", subword_s)
            s.balanced_vector[s[head]] +=_sage_const_1 
            t.balanced_vector[t[head]] +=_sage_const_1 
            # print("s.balanced_vector:", s.balanced_vector)
            # print("t.balanced_vector:", t.balanced_vector)
            if s.balanced_vector==t.balanced_vector:
                A.append((str(s[startpos:head+_sage_const_1 ]), str(t[startpos:head+_sage_const_1 ])))
                # print("A+:", [s[startpos:head+1], t[startpos:head+1]])
                # print("head:" , head)
                startpos = head + _sage_const_1 
                s.balanced_vector = Reset_balanced_vector(s) 
                t.balanced_vector = Reset_balanced_vector(t) 
    return A

def Balanced_pair_alphabet(s,t, n=_sage_const_1000 ):
    return set(Balanced_pair_list(s,t, n))

def Lifted_Morphism(s,A):
    """
    Lift a morphism to a new morphism.
    
    Args:
        s (WordMorphism): The input morphism.
        A (alphabet): The set of balanced pairs.
    
    Returns:
        WordMorphism: The lifted morphism.
    """  
    # print("s:", s)
    # print("s._letter:", s._letter)
    # print("s._letter:", s._letter)
    # print("s._letter:", s._letter)
    lifted_morphism = {}
    lifted_alphabet = set(list(A))
    for balanced_pair in A:
        # print("balanced_pair:", balanced_pair)
        # print("lifted_alphabet:", lifted_alphabet)
        lifted_morphism[balanced_pair] = Balanced_pair_list(Word(balanced_pair[_sage_const_0 ]).apply_morphism(s),Word(balanced_pair[_sage_const_1 ]).apply_morphism(s))
        # print("lifted_morphism[balanced_pair]:", lifted_morphism[balanced_pair])
        # print("set lifted_morphism[balanced_pair]:", set(lifted_morphism[balanced_pair]))
        lifted_alphabet = lifted_alphabet.union(set(lifted_morphism[balanced_pair]))
    return (WordMorphism(lifted_morphism),lifted_alphabet)


# Example usage:
s = WordMorphism({'0': '01', '1': '02', '2': '0'})
F = s.fixed_point("0")
print("F.parent:", F.parent().alphabet())
result = Balanced_pair_alphabet(F, F[_sage_const_1 :])
print("balanced pair alphabet:", result)
print("Lifted_Morphism:", Lifted_Morphism(s, result))
mor = s
alpha_0 = result
for i in range(_sage_const_30 ):
    (mor,alpha_1) = Lifted_Morphism(s, alpha_0)
    # print("alpha_1:", alpha_1)
    # print("alpha_0:", alpha_0)
    if len(alpha_1.difference(alpha_0))==_sage_const_0 :
        break
    alpha_0 = alpha_1
    # print("Lifted_Morphism alphabet:", mor.domain())
# print("Lifted_Morphism:", mor)
print(latex(mor))

